#!/bin/bash
set -e
set -x

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/rancher-ingress .
cp ../lbprovider/{haproxy_reload,haproxy_template.cfg} .

docker build -t ${REPO}/rancher-ingress:${TAG} .

echo Built ${REPO}/rancher-ingress:${TAG}
