#!/bin/bash
set -e

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

for dir in */
do
    cd $dir
    provider_type=${dir%/}
    cp ../../bin/lb-controller .
    cp -r ../../provider/${provider_type}/scripts scripts
    cp -r ../../provider/${provider_type}/config config
    docker build -t ${REPO}/lb-service-${provider_type}:${TAG} .
    echo Built ${REPO}/lb-service-${provider_type}:${TAG}
    cd ..
done
