#!/bin/bash
set -e

reload_haproxy()
{
    # apply new config
    if haproxy -p /var/run/haproxy.pid -f $1 -sf $(cat /var/run/haproxy.pid); then
        return 0
    else
        return 1
    fi
}

reload_haproxy /etc/haproxy/haproxy.cfg

